GOOGLE_APP_ID: '182931253359-1d6265uujvvo2v2m6nhohn0s3ge876lv.apps.googleusercontent.com'
GOOGLE_APP_SECRET: 'wj4pDAI_XkG5uFxp4KfD8jHP'

FACEBOOK_APP_ID: '288890231441906'
FACEBOOK_APP_SECRET: '5e7423b56d3ba037da5a97ff6e8bd17f'
AWS_KEY: 'AKIAJMZPQ6BHEBL52FDQ'
AWS_SECRET: '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'